/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 ./Hen.glb --transform --keepnames --keepmeshes --types
*/

import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Geo_Hen: THREE.Mesh;
  };
  materials: {
    lambert2SG: THREE.MeshStandardMaterial;
  };
};

export function Hen(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Hen-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group scale={0.03}>
        <mesh
          name="Geo_Hen"
          geometry={nodes.Geo_Hen.geometry}
          material={materials.lambert2SG}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Hen-transformed.glb");
