/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 ./model.gltf --transform --keepnames --types --keepmeshes --simplify
*/

import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";

export type Model = GLTF & {
  nodes: {
    Cube683: THREE.Mesh;
    Cube728: THREE.Mesh;
    Cube003: THREE.Mesh;
    Cube021: THREE.Mesh;
    Plane010: THREE.Mesh;
    Plane011: THREE.Mesh;
    Plane003: THREE.Mesh;
    Cube001: THREE.Mesh;
    Cube004: THREE.Mesh;
    Cube029: THREE.Mesh;
    Cube031: THREE.Mesh;
    Cube030: THREE.Mesh;
    Cube034: THREE.Mesh;
    Cube038: THREE.Mesh;
    Cube040: THREE.Mesh;
    Cube041: THREE.Mesh;
    Cube017: THREE.Mesh;
    Cube012: THREE.Mesh;
    Cube026: THREE.Mesh;
    Cube027: THREE.Mesh;
    Cube020: THREE.Mesh;
    Cube022: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube704: THREE.Mesh;
    Cube405: THREE.Mesh;
    Cube652: THREE.Mesh;
    Cube228: THREE.Mesh;
    Cube023: THREE.Mesh;
    Cube680: THREE.Mesh;
    Cube005: THREE.Mesh;
    Plane008: THREE.Mesh;
    Plane002: THREE.Mesh;
    Plane006: THREE.Mesh;
    Plane007: THREE.Mesh;
    Plane005: THREE.Mesh;
    Plane004: THREE.Mesh;
    Cube702: THREE.Mesh;
    Cube024: THREE.Mesh;
    Cube546: THREE.Mesh;
    Cube547: THREE.Mesh;
    Cube013: THREE.Mesh;
    Cube556: THREE.Mesh;
    Cube703: THREE.Mesh;
    Cube018: THREE.Mesh;
    Cube019: THREE.Mesh;
    Cube032: THREE.Mesh;
    Cube035: THREE.Mesh;
    Cube042: THREE.Mesh;
    Cube025: THREE.Mesh;
    Cube036: THREE.Mesh;
    Cube039: THREE.Mesh;
    Cube044: THREE.Mesh;
    Cube046: THREE.Mesh;
    Cube047: THREE.Mesh;
    Cube052: THREE.Mesh;
    Cube028: THREE.Mesh;
    Cube033: THREE.Mesh;
    Cube050: THREE.Mesh;
    Plane001: THREE.Mesh;
    Cube053: THREE.Mesh;
    Plane013: THREE.Mesh;
    Cube048: THREE.Mesh;
    Cube051: THREE.Mesh;
    Plane016: THREE.Mesh;
    Plane025: THREE.Mesh;
    Plane026: THREE.Mesh;
    Text002: THREE.Mesh;
    Text003: THREE.Mesh;
    Cube037: THREE.Mesh;
    Cube049: THREE.Mesh;
    Cube055: THREE.Mesh;
    Cube056: THREE.Mesh;
    Plane009: THREE.Mesh;
    Plane022: THREE.Mesh;
    Plane030: THREE.Mesh;
    Cube247: THREE.Mesh;
    Cube060: THREE.Mesh;
    Cube061: THREE.Mesh;
    Cube062: THREE.Mesh;
    Cube011: THREE.Mesh;
    Cube014: THREE.Mesh;
    Plane021: THREE.Mesh;
    Cube016: THREE.Mesh;
    Cube059: THREE.Mesh;
    Cube598: THREE.Mesh;
    Plane032: THREE.Mesh;
    Plane033: THREE.Mesh;
    Plane035: THREE.Mesh;
    Plane036: THREE.Mesh;
    Plane034: THREE.Mesh;
    Cube068: THREE.Mesh;
    Plane014: THREE.Mesh;
    Cube006: THREE.Mesh;
    Cube007: THREE.Mesh;
    Cube008: THREE.Mesh;
    Plane017: THREE.Mesh;
    Plane019: THREE.Mesh;
    Cube009: THREE.Mesh;
    Cube043: THREE.Mesh;
    Plane015: THREE.Mesh;
    Plane018: THREE.Mesh;
    Plane023: THREE.Mesh;
    Plane027: THREE.Mesh;
    Sphere001: THREE.Mesh;
    Cube685: THREE.Mesh;
    Cube698: THREE.Mesh;
    Cube054: THREE.Mesh;
    Cylinder002: THREE.Mesh;
    Plane024: THREE.Mesh;
    Cube058: THREE.Mesh;
    Cube063: THREE.Mesh;
    Cube080: THREE.Mesh;
    Cube065: THREE.Mesh;
    Cube071: THREE.Mesh;
    Cube072: THREE.Mesh;
    Cube069: THREE.Mesh;
    Cube084: THREE.Mesh;
    Cube090: THREE.Mesh;
    Cube075: THREE.Mesh;
    Cube076: THREE.Mesh;
    Cube085: THREE.Mesh;
  };
  materials: {
    Wood_Dark: THREE.MeshPhysicalMaterial;
    Marble: THREE.MeshPhysicalMaterial;
  };
};

export function useModel() {
  const { nodes, materials } = useGLTF("/model-transformed.glb") as Model;

  return { nodes, materials };
}

useGLTF.preload("/model-transformed.glb");
